### PR TITLE
Create jp.json

### PR DESCRIPTION
**Pull request by Vladimir-Imaichi**
Hello
I have created a translation file for Japanese.
Could you please review it for me?

### CODE REVIEW

**Comment by nicehashdev** [comment]
Hello!

Can you please also state here in comments how do you call your language (written) in Japanese. Such as we do it for "English" or "Deutsch" (German language). Because I need to change [avail1.json file](https://github.com/nicehash/NiceHashQuickMiner/blob/main/lang/avail1.json) as well.

And thank you for your contribution!

**Comment by Vladimir-Imaichi** [comment]
Hi

Thanks for the reply.
Japanese is written "日本語" in Japanese language.

**Comment by nicehashdev** [comment]
Also please, check https://github.com/nicehash/NiceHashQuickMiner/blob/main/lang/UPDATES.md and make corrections + update your file to version 4. Thanks!

**Comment by nicehashdev** [comment]
Thanks!

I had to rename your file to ja,json, because according to [ISO standard](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) two letter code is **ja** and not **jp**.

Do you have BTC wallet to receive small tip for doing this?

**Comment by Vladimir-Imaichi** [comment]
Hi.

I'm really glad you merged the file.
Of course I have. Because I'm a Nicehash user :)
How can I tell you my address?

**Comment by nicehashdev** [comment]
If you use discord, join NiceHash channel and contact me djeZo888 (purple nick).

**Comment by Vladimir-Imaichi** [comment]
Thanks! I send a message from a*u*a.
I want to go to Triglavski narodni park :)

**Pull request merged**
